--Setting up
SELECT * FROM TAIKHOAN;

INSERT INTO TAIKHOAN (USERNAME, PASSWORD) VALUES ('admin', '123');

create user loclaai identified by Oracle123456;
grant dba to loclaai;

SELECT * FROM TAIKHOAN;

-- Create Table
CREATE TABLE TAIKHOAN( 
	USERNAME VARCHAR2(255),
	PASSWORD VARCHAR2(255)
);

CREATE TABLE KHACHHANG ( 
	HO VARCHAR2(10),
	TEN VARCHAR2(10),
	SDT VARCHAR2(20),
	EMAIL VARCHAR2(255),
	USERNAME VARCHAR2(255)
);

CREATE TABLE NHANVIEN ( 
	HO VARCHAR2(10),
	TEN VARCHAR2(10),
	SDT VARCHAR2(20),
	EMAIL VARCHAR2(255),
	USERNAME VARCHAR2(255)
);

CREATE TABLE TOUR(
	MATOUR VARCHAR2(255)
);

CREATE TABLE CHUYEN(
	MACHUYEN VARCHAR2(255),
	TENCHUYEN VARCHAR2(255),
	NGAYDI VARCHAR2(255),
	NGAYDEN VARCHAR2(255),
	GIACHUYEN VARCHAR2(255),
	SOLUONGVE NUMBER,
	MATOUR VARCHAR2(255)
);

CREATE TABLE DANGKY (
	MACHUYEN VARCHAR2(255),
	USERNAME VARCHAR2(255),
	SL NUMBER
);

-- Test Procedure
CREATE OR REPLACE PROCEDURE fetchCHUYEN ( 
  p_tour_id IN VARCHAR2
)
AS
  v_cursor SYS_CURSOR;
BEGIN
  OPEN v_cursor FOR
    SELECT *
    FROM CHUYEN
    WHERE MATOUR = p_tour_id;
  FOR rec IN v_cursor LOOP
    DBMS_OUTPUT.PUT_LINE('MACHUYEN: ' || rec.MACHUYEN);
    DBMS_OUTPUT.PUT_LINE('TENCHUYEN: ' || rec.TENCHUYEN);
    DBMS_OUTPUT.PUT_LINE('NGAYDI: ' || rec.NGAYDI);
    DBMS_OUTPUT.PUT_LINE('NGAYDEN: ' || rec.NGAYDEN);
    DBMS_OUTPUT.PUT_LINE('GIACHUYEN: ' || rec.GIACHUYEN);
    DBMS_OUTPUT.PUT_LINE('SOLUONGVE: ' || rec.SOLUONGVE);
    DBMS_OUTPUT.PUT_LINE('MATOUR: ' || rec.MATOUR);
    DBMS_OUTPUT.PUT_LINE('--------------------');
  END LOOP;

  CLOSE v_cursor;
END;

-- Insert data

INSERT INTO TAIKHOAN VALUES('admin','a123')
INSERT INTO TAIKHOAN VALUES('kh','a123')
INSERT INTO CHUYEN (MACHUYEN, TENCHUYEN, NGAYDI, NGAYDEN, GIACHUYEN, SOLUONGVE,MATOUR)
VALUES ('HN101', 'Ha Noi - Da Nang', '2024-06-17', '2024-06-17', '800', 1);
INSERT INTO CHUYEN (MACHUYEN, TENCHUYEN, NGAYDI, NGAYDEN, GIACHUYEN, SOLUONGVE,MATOUR)
VALUES ('NT202', 'Nha Trang - Phu Quoc', '2024-06-20', '2024-06-20', '1500', 1);
INSERT INTO CHUYEN (MACHUYEN, TENCHUYEN, NGAYDI, NGAYDEN, GIACHUYEN, SOLUONGVE,MATOUR)
VALUES ('DN303', 'Da Nang - Ho Chi Minh City', '2024-06-23', '2024-06-23', '900', 1);
INSERT INTO CHUYEN (MACHUYEN, TENCHUYEN, NGAYDI, NGAYDEN, GIACHUYEN, SOLUONGVE,MATOUR)
VALUES ('CT404', 'Can Tho - Con Dao', '2024-06-25', '2024-06-25', '1200', 1);
INSERT INTO CHUYEN (MACHUYEN, TENCHUYEN, NGAYDI, NGAYDEN, GIACHUYEN, SOLUONGVE,MATOUR)
VALUES ('HL505', 'Ha Long - Hai Phong', '2024-06-27', '2024-06-27', '300', 1);
