/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dulich.View;

import dulich.Model.DataAccess;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public final class Profile extends javax.swing.JPanel {
    public DataAccess data;
    private String idtk;
    private String role;
    /**
     * Creates new form TourForm
     */
    public Profile(String idtk, String role) {
        initComponents();
        setVisible(true);
        data = new DataAccess();
        this.idtk = idtk;
        this.role = role;
        fetchProfile();
    }
    public void fetchProfile() {
        String sqlquery;
        if (role.equals("NV")) {
            sqlquery = "SELECT * FROM NHANVIEN WHERE USERNAME=?";
        }   else {
            sqlquery = "SELECT * FROM KHACHHANG WHERE USERNAME=?";
        }
//            JOptionPane.showMessageDialog(null, idtk);
//            JOptionPane.showMessageDialog(null, role);
//            JOptionPane.showMessageDialog(null, sqlquery);
                try{
//                      String sqlquery = "SELECT * FROM NHANVIEN WHERE USERNAME=?";
                      PreparedStatement pst = data.getConnection().prepareStatement(sqlquery);
                      pst.setString(1,idtk);
                      ResultSet rs=pst.executeQuery();
                      while (rs.next()) {
                        if  (!((rs.getString(1))==null)) {
                            txtHO.setText(rs.getString(1));
                            txHO.setText(rs.getString(1));
                        }
                        if  (!((rs.getString(2))==null)) {
                            txtTEN.setText(rs.getString(2));
                            txTEN.setText(rs.getString(2));
                        }
                        if  (!((rs.getString(3))==null)) {
                            txtSDT.setText(rs.getString(3));
                            txSDT.setText(rs.getString(3));
                        }
                        if  (!((rs.getString(4))==null)) {
                            txtEMAIL.setText(rs.getString(4));
                            txEMAIL.setText(rs.getString(4));
                        }

                      }
                      
                      

                      
                  }catch(HeadlessException | SQLException e){
                      JOptionPane.showMessageDialog(null, e);
                  }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundJPanel9 = new dulich.Swing.RoundJPanel();
        jLabel6 = new javax.swing.JLabel();
        roundJPanel4 = new dulich.Swing.RoundJPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();
        txtHO = new javax.swing.JLabel();
        txtTEN = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JLabel();
        roundJPanel10 = new dulich.Swing.RoundJPanel();
        txHO = new dulich.Swing.PlaceholderText();
        txtTEN1 = new javax.swing.JLabel();
        roundJPanel1 = new dulich.Swing.RoundJPanel();
        txTEN = new dulich.Swing.PlaceholderText();
        txtTEN2 = new javax.swing.JLabel();
        roundJPanel2 = new dulich.Swing.RoundJPanel();
        txSDT = new dulich.Swing.PlaceholderText();
        txtTEN3 = new javax.swing.JLabel();
        txtTEN4 = new javax.swing.JLabel();
        roundJPanel3 = new dulich.Swing.RoundJPanel();
        txEMAIL = new dulich.Swing.PlaceholderText();
        txtTEN5 = new javax.swing.JLabel();
        txtTEN6 = new javax.swing.JLabel();
        txtTEN7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        roundJPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundJPanel9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roundJPanel9MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("CẬP NHẬT");

        javax.swing.GroupLayout roundJPanel9Layout = new javax.swing.GroupLayout(roundJPanel9);
        roundJPanel9.setLayout(roundJPanel9Layout);
        roundJPanel9Layout.setHorizontalGroup(
            roundJPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        roundJPanel9Layout.setVerticalGroup(
            roundJPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel11.setText("Xin chào");

        txtSDT.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtSDT.setText("SDT");

        txtHO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtHO.setText("Họ");

        txtTEN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtTEN.setText("Tên");

        txtEMAIL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtEMAIL.setText("Email");

        javax.swing.GroupLayout roundJPanel4Layout = new javax.swing.GroupLayout(roundJPanel4);
        roundJPanel4.setLayout(roundJPanel4Layout);
        roundJPanel4Layout.setHorizontalGroup(
            roundJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(roundJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtSDT)
                    .addGroup(roundJPanel4Layout.createSequentialGroup()
                        .addComponent(txtHO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTEN))
                    .addComponent(txtEMAIL))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        roundJPanel4Layout.setVerticalGroup(
            roundJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHO)
                    .addComponent(txtTEN))
                .addGap(18, 18, 18)
                .addComponent(txtSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txtEMAIL)
                .addContainerGap())
        );

        roundJPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundJPanel10MouseClicked(evt);
            }
        });

        txHO.setBackground(new java.awt.Color(195, 243, 255));
        txHO.setForeground(new java.awt.Color(0, 0, 0));
        txHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundJPanel10Layout = new javax.swing.GroupLayout(roundJPanel10);
        roundJPanel10.setLayout(roundJPanel10Layout);
        roundJPanel10Layout.setHorizontalGroup(
            roundJPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txHO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        roundJPanel10Layout.setVerticalGroup(
            roundJPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTEN1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTEN1.setText("Họ:");

        txTEN.setBackground(new java.awt.Color(195, 243, 255));
        txTEN.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout roundJPanel1Layout = new javax.swing.GroupLayout(roundJPanel1);
        roundJPanel1.setLayout(roundJPanel1Layout);
        roundJPanel1Layout.setHorizontalGroup(
            roundJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txTEN, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        roundJPanel1Layout.setVerticalGroup(
            roundJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txTEN, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTEN2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTEN2.setText("Email:");

        txSDT.setBackground(new java.awt.Color(195, 243, 255));
        txSDT.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout roundJPanel2Layout = new javax.swing.GroupLayout(roundJPanel2);
        roundJPanel2.setLayout(roundJPanel2Layout);
        roundJPanel2Layout.setHorizontalGroup(
            roundJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundJPanel2Layout.setVerticalGroup(
            roundJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTEN3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTEN3.setText("SĐT:");

        txtTEN4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTEN4.setText("Tên:");

        txEMAIL.setBackground(new java.awt.Color(195, 243, 255));
        txEMAIL.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout roundJPanel3Layout = new javax.swing.GroupLayout(roundJPanel3);
        roundJPanel3.setLayout(roundJPanel3Layout);
        roundJPanel3Layout.setHorizontalGroup(
            roundJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundJPanel3Layout.setVerticalGroup(
            roundJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundJPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txEMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTEN5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTEN5.setText("Ứng dụng đặt du lịch");

        txtTEN6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTEN6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dulich/View/1179225-200.png"))); // NOI18N
        txtTEN6.setText("Mèo Vi Vu");

        txtTEN7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTEN7.setText("hàng đầu Việt Nam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roundJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTEN6)
                                            .addComponent(txtTEN5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(txtTEN7))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(roundJPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(roundJPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtTEN3)
                                    .addComponent(txtTEN1))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTEN4)
                                    .addComponent(txtTEN2)
                                    .addComponent(roundJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roundJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(roundJPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTEN6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTEN5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTEN7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTEN1)
                    .addComponent(txtTEN4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundJPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTEN2)
                    .addComponent(txtTEN3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundJPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(roundJPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundJPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundJPanel10MouseClicked

    }//GEN-LAST:event_roundJPanel10MouseClicked

    private void roundJPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundJPanel9MouseClicked
    }//GEN-LAST:event_roundJPanel9MouseClicked

    private void txHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHOActionPerformed

    private void roundJPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundJPanel9MousePressed
                String HO = txHO.getText();
        String TEN = txTEN.getText();
        String SDT = txSDT.getText();
        String EMAIL = txEMAIL.getText();
        String sqlquery;
        if (role.equals("NV")) {
            sqlquery = "UPDATE NHANVIEN SET HO = ?, TEN = ?, SDT = ?, EMAIL =?  WHERE USERNAME = ?";
        }   else {
            sqlquery = "UPDATE KHACHHANG SET HO = ?, TEN = ?, SDT = ?, EMAIL =?  WHERE USERNAME = ?";
        }
        try{
                      PreparedStatement pst = data.getConnection().prepareStatement(sqlquery);
                      pst.setString(5,idtk);
                      pst.setString(1,HO);
                      pst.setString(2,TEN);
                      pst.setString(3,SDT);
                      pst.setString(4,EMAIL);
                      ResultSet rs=pst.executeQuery();
                  }catch(HeadlessException | SQLException e){
                      JOptionPane.showMessageDialog(null, e);
                  }
//        JOptionPane.showMessageDialog(null, "update");
        fetchProfile();
    }//GEN-LAST:event_roundJPanel9MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private dulich.Swing.RoundJPanel roundJPanel1;
    private dulich.Swing.RoundJPanel roundJPanel10;
    private dulich.Swing.RoundJPanel roundJPanel2;
    private dulich.Swing.RoundJPanel roundJPanel3;
    private dulich.Swing.RoundJPanel roundJPanel4;
    private dulich.Swing.RoundJPanel roundJPanel9;
    private dulich.Swing.PlaceholderText txEMAIL;
    private dulich.Swing.PlaceholderText txHO;
    private dulich.Swing.PlaceholderText txSDT;
    private dulich.Swing.PlaceholderText txTEN;
    private javax.swing.JLabel txtEMAIL;
    private javax.swing.JLabel txtHO;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtTEN;
    private javax.swing.JLabel txtTEN1;
    private javax.swing.JLabel txtTEN2;
    private javax.swing.JLabel txtTEN3;
    private javax.swing.JLabel txtTEN4;
    private javax.swing.JLabel txtTEN5;
    private javax.swing.JLabel txtTEN6;
    private javax.swing.JLabel txtTEN7;
    // End of variables declaration//GEN-END:variables
}
